# Generated by Django 4.2.1 on 2023-06-20 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Фамилия, имя, отчество')),
                ('email', models.CharField(max_length=150)),
                ('comment', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая рассылка', max_length=100, verbose_name='Название рассылки')),
                ('time', models.TimeField(default='0:00:00', verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='monthly', max_length=12, verbose_name='Периодичность рассылки')),
                ('start_day', models.DateField(default='2001-01-01', verbose_name='Дата начала рассылки')),
                ('status', models.CharField(choices=[('finished', 'завершена'), ('created', 'создана'), ('run', 'запущена')], default='created', max_length=9, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('time', 'period', 'status'),
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок сообщения')),
                ('text', models.CharField(max_length=500, verbose_name='Текст сообщения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активный')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('title', 'text'),
            },
        ),
        migrations.CreateModel(
            name='MailingAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_daytime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время последней попытки')),
                ('server_answer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ почтового сервера')),
                ('status', models.CharField(blank=True, choices=[('successfully', 'успешно'), ('unsuccessfully', 'неудачно')], max_length=14, null=True, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная')),
                ('mayling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
                'ordering': ('mailing_daytime', 'server_answer'),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.usermessage', verbose_name='Сообщение'),
        ),
    ]
