# Generated by Django 4.2.1 on 2023-05-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default='0:00:00', verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('daily', 'раз в день'), ('weekly', 'раз в неделю'), ('monthly', 'раз в месяц')], default='monthly', max_length=12, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('finished', 'завершена'), ('created', 'создана'), ('run', 'запущена')], default='created', max_length=9, verbose_name='Статус рассылки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активная')),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.usermessage')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('time', 'period', 'status'),
            },
        ),
    ]
