# Generated by Django 4.2.1 on 2023-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Новая рассылка', max_length=100, verbose_name='Название рассылки'),
        ),
    ]
