# Generated by Django 4.2.1 on 2023-05-28 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_mailingattempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='user_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.usermessage', verbose_name='Сообщнение'),
        ),
        migrations.AlterField(
            model_name='mailingattempts',
            name='mayling',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Рассылка'),
        ),
    ]
