# Generated by Django 4.2.1 on 2023-05-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_mailing_start_day_alter_mailing_user_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_day',
            field=models.DateField(default='2001-01-01', verbose_name='Дата начала рассылки'),
        ),
    ]
